version: '3.8'

services:
  postgres:
    image: postgres:16.2
    container_name: nest_htmx_pgdb
    ports:
      - '5432:5432'
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_DB: mydatabase
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    networks:
      - nest_htmx_network

networks:
  nest_htmx_network:
    driver: bridge
